apiVersion: v1
kind: Service
metadata:
  name: appdb
spec:
  selector:
    app: appdb
  ports:
    - protocol: TCP
      port: 5432
        # targetPort: 5432 // by default the targetPort is set to port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-db
  labels:
    app: app-db 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: app-db
          image: postgres
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USERNAME
            value: postgres
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-be-secret
                key: dbpassword
