apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-be-deployment 
  # labels are matched to attach services to the pods and also attach pods to deployments
  labels:
    app: app-be
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: app-be
  template:
    metadata:
      labels:
        app: app-be
    spec:
      containers:
      - name: app-be
        image: {{ .Values.backendImage }}
        imagePullPolicy: Never # Otherwise It will try and pull it from dockerhub
        ports:
        - containerPort: 8000
        env:
        - name: JWT_SECRET
          value: {{ .Values.jwtSecret }}
        - name: DB_ADDR
          valueFrom:
            configMapKeyRef:
              name: app-be-configmap
              key: db_addr
---
apiVersion: v1
kind: Service
metadata:
  name: app-be-service
spec:
  selector:
    app: app-be
  type: LoadBalancer # The normal type also does load balancing.
    # The only difference is that to get external ip i need to set it to this type.
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000 # make it available to the external ip

